apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: s3-lambda-terraform-${{values.name}}
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  path: ./tf-patterns/s3-lambda-terraform
  approvePlan: auto
  retryInterval: 10s
  interval: 2m
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: "s3-lambda-terraform-${{values.name}}-git-repository"
    namespace: flux-system
  varsFrom:
    - kind: ConfigMap
      name: "s3-lambda-terraform-${{values.name}}-tf-cm"