apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.appname}}-dev-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ${{values.namespace}}
    name: dev-cluster
  source:
    repoURL: http://${{values.hostname}}/gitea/giteaAdmin/${{values.appname}}
    targetRevision: main
    path: deployment/dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true