---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.appname}}-operate-workflow-sa
  namespace: ${{values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{values.appname}}-operate-workflow-sa-binding
  namespace: ${{values.namespace}}
subjects:
- kind: ServiceAccount
  name: ${{values.appname}}-operate-workflow-sa
  namespace: ${{values.namespace}}
roleRef:
  kind: ClusterRole
  name: argo-workflows-server
  apiGroup: rbac.authorization.k8s.io

