apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicd-${{values.appname}}
  description: Deploy CI/CD Pipeline for ${{ values.appname }}
  annotations:
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/kubernetes-id: cicd-${{values.appname}}
    argocd/app-name: cicd-${{values.appname | dump}}
  links:
    - url: https://${{values.hostname}}/gitea?repo=${{values.appname}}
      title: Repo URL
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: ${{values.appname | dump}}

