apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.appname}}-cicd-provisioner
  namespace: ${{values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{values.appname}}-cicd-provisioner-binding
  namespace: ${{values.namespace}}
subjects:
- kind: ServiceAccount
  name: ${{values.appname}}-cicd-provisioner
  namespace: ${{values.namespace}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# PodIdentityAssociation
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: "${{values.appname}}-cicd-provisioner-podidentity"
spec:
  forProvider:
    clusterName: "modern-engineering"
    namespace: "${{values.namespace}}"
    region: "${{values.aws_region}}"
    roleArnRef:
      name: "${{values.appname}}-cicd-provisioner-iam-role"
    serviceAccount: "${{values.appname}}-cicd-provisioner"

---
# IAM Role
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: "${{values.appname}}-cicd-provisioner-iam-role"
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "pods.eks.amazonaws.com"
            },
            "Action": [
              "sts:AssumeRole",
              "sts:TagSession"
            ]
          }
        ]
      }

---
# IAM Policy
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: "${{values.appname}}-cicd-provisioner-ecr-access-policy"
spec:
  forProvider:
    description: ECR Access Policy
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "ecr:GetAuthorizationToken",
              "ecr:GetRepositoryPolicy",
              "ecr:DescribeRepositories",
              "ecr:CreateRepository",
              "ecr:BatchCheckLayerAvailability",
              "ecr:GetDownloadUrlForLayer",
              "ecr:ListImages",
              "ecr:DescribeImages",
              "ecr:BatchGetImage",
              "ecr:GetLifecyclePolicy",
              "ecr:GetLifecyclePolicyPreview",
              "ecr:ListTagsForResource",
              "ecr:DescribeImageScanFindings",
              "ecr:InitiateLayerUpload",
              "ecr:UploadLayerPart",
              "ecr:CompleteLayerUpload",
              "ecr:PutImage"

            ],
            "Resource": "*"
          }
        ]
      }

---
# IAM Policy Attachment
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: "${{values.appname}}-cicd-provisioner-ecr-access-policy-attachment"
spec:
  forProvider:
    policyArnRef:
      name: "${{values.appname}}-cicd-provisioner-ecr-access-policy"
    roleRef:
      name: "${{values.appname}}-cicd-provisioner-iam-role"
