apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-deploy-without-git-repo
  title: App Deployment without Git Repo
  description: Creates a ArgocCD for deploying an App for an existing Git Repo
  tags:
    - app-deploy
    - gitea
    - argocd
spec:
  owner: guest
  type: service
  parameters:
    - title: Provide App Information
      required:
        - appName
        - repoPath
        - repoName
        - environment
      properties:
        appName:
          title: App Name
          type: string
          description: Name of the App
        environment:
          title: Environment
          type: string
          description: The environment (e.g., dev, prod)
          enum: ['dev-cluster', 'prod-cluster', 'in-cluster']
        repoName:
          title: Repo Name of your Gitea Repo integrated with Backstage
          type: string
          pattern: ^[a-zA-Z0-9-_.]+$
        repoPath:
          title: Path of Git Repo to sync for GitOps
          type: string
        appNamespace:
          title: App Namespace
          type: string
          description: The namespace where the app should be deployed
          default: default
  steps:
    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.appName}}
        appNamespace: ${{parameters.appNamespace}}
        argoInstance: ${{parameters.environment}}
        projectName: default
        repoUrl: http://my-gitea-http.gitea.svc.cluster.local:3000/giteaAdmin/${{parameters.repoName}}
        path: ${{parameters.repoPath}}
    - id: template-output
      name: Template Output
      action: debug:log
      input:
        listWorkspace: true
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
