apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Set up an S3 bucket that triggers a Lambda function to log object creation events
  name: s3-lambda-terraform
  title: S3 to Lambda
spec:
  owner: guest
  type: service
  parameters:
    - properties:
        tfVars:
          title: Terraform variables
          properties:
            name:
              title: Name for the build
              type: string
            aws_region:
              description: AWS Region
              type: string
          required:
            - name
            - aws_region
          type: object
        repoUrl:
          description: Gitea URL on management cluster
          title: Gitea URL
          type: string
        adminRoleName:
          description: Name of the role to give the administrative rights
          title: Admin role name
          type: string
        namespace:
          default: flux-system
          title: Existing namespace to create this resource
          type: string
      title: Configuration options
      required:
        - repoUrl
  steps:
    - action: fetch:template
      id: fetch-base
      input:
        url: ./template-s3-lambda-terraform/
        values:
          adminRoleName: ${{parameters.adminRoleName}}
          name: ${{parameters.tfVars.name}}
          namespace: ${{parameters.namespace}}
          tfVars: ${{parameters.tfVars}}
      name: Fetch Base
    - id: publish
      name: Publishing to a gitea git repository
      action: publish:gitea
      input:
        description: Example of S3 to Lambda
        # Hard coded value for this demo purposes only.
        repoUrl: ${{parameters.repoUrl}}?repo=${{parameters.tfVars.name}}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.tfVars.name}}
        appNamespace: ${{parameters.namespace}}
        argoInstance: in-cluster
        projectName: default
        # necessary until we generate our own cert
        repoUrl: http://my-gitea-http.gitea.svc.cluster.local:3000/giteaAdmin/${{parameters.tfVars.name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}