apiVersion: batch/v1
kind: Job
metadata:
  name: create-dev-and-prod-env-${{values.name}}
  namespace: flux-system
spec:
  template:
    spec:
      serviceAccountName: tf-runner
      containers:
      - name: trigger
        image: amazon/aws-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          aws --region ${{values.aws_region}} codebuild start-build --project-name modernengg-codebuild
      restartPolicy: Never
