apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: "stepfunctions-bedrock-terraform-${{values.name}}-git-repository"
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  interval: 5m
  timeout: 3m
  url: https://github.com/aws-samples/appmod-partners-serverless.git
  ref:
    branch: main