apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates Amazon RDS Database with CrossPlane
  name: db-cluster-rds
  title: Creates an Amazon RDS Database
spec:
  owner: guest
  type: service
  parameters:
    - properties:
        name:
          title: Application Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        namespace:
          default: flux-system
          title: namespace within the kubernetes cluster to deploy this
          type: string
        region:
          title: aws region
          type: string
        subnetIds:
          title: Subnet IDs
          description: ID of subnets for rds cluster
          type: array
          items:
            type: string
        repoUrl:
          title: Gitea URL
          type: string
          description: Gitea URL on Management cluster
      title: Configuration Options
      required:
        - name
        - repoUrl
        - region
        - subnetIds
  steps:
    - action: fetch:template
      id: fetch-base
      input:
        url: ./skeleton/
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          region: ${{ parameters.region }}
          repoUrl: ${{parameters.repoUrl}}
          subnetIds: ${{parameters.subnetIds}}
      name: Fetch Base
    - id: publish
      name: Publishing to a gitea git repository
      action: publish:gitea
      input:
        description: RDS Cluster manifests
        # Hard coded value for this demo purposes only.
        repoUrl: ${{parameters.repoUrl}}?repo=${{parameters.name}}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.namespace}}
        argoInstance: in-cluster
        projectName: default
        # necessary until we generate our own cert
        repoUrl: http://my-gitea-http.gitea.svc.cluster.local:3000/giteaAdmin/${{parameters.name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}

